### ISSUE TITLE
Error in bioinfscripts/circularAnnotator.r

### ISSUE THREAD

**Issue by sarah872** [gringer/bioinfscripts#6]
I am getting an error when executing the `circularAnnotator.r`

```
Error in .geometry(width, height, units, res) : object 'sizeX' not found
Calls: png -> .geometry
Execution halted
```

**Comment by gringer** [comment]
That's a bit odd. `sizeX` is declared earlier in the code. How are you running it?

You should be running from the command line, something like this:

    ./circularAnnotator.r <gff3 file> <genome size> [options]
